### ISSUE TITLE
Elasticsearch-dsl version triggering error

### ISSUE THREAD

**Issue by silascutler** [geudrik/darkstar#1] opened 2020-07-01 19:43 UTC
Elasticsearch_dsl version == 7.2.1

```
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 42, in hello_world
    Domain.init()  # TODO: This is .. bad. Fix how this is being done
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/document.py", line 138, in init
    i.save(using=using)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/index.py", line 274, in save
    if not self.exists(using=using):
  File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/index.py", line 385, in exists
    return self._get_connection(using).indices.exists(index=self._name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 307, in exists
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 345, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 245, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(encoding with 'idna' codec failed (UnicodeError: label too long)) caused by: UnicodeError(encoding with 'idna' codec failed (UnicodeError: label too long))```

**Comment by geudrik** [comment] 2020-07-02 11:52
Yeah, I knew Unicode would be an issue. It's on my to-do list to fix, I haven't had time the last few days to go through more of it. Thanks for the bug! 

I'm guessing you were just trying to insert a unicode url?

**Comment by geudrik** [comment] 2020-07-02 12:00
Actually, this is a Python bug in the socket library. Interesting. I'll have to take a different approach to do name resolutions.

https://bugs.python.org/issue32958

@silascutler ping me on keybase if you would if you're able to share the url. I suspect the issue is simply that you ran into the above bug with `socket.getaddrinfo`

Edit: if I'm reading the DNS RFC right (https://www.ietf.org/rfc/rfc1035.txt) each label (think "subdomain") in a domain name cannot exceed 64chars in length (TIL). I have absolutely zero handling of punycode urls currently (coming). So without knowing the domain you tried, I'm sort of grasping at straws

**Comment by geudrik** [comment] 2020-07-03 17:46
Looks like this was an issue with string formatting gone wild. Fixed with https://github.com/geudrik/darkstar/commit/b4a71c69251af7e68bdf5222b29d7928cd602e3d#diff-348c611119c690bb7aa9a355d89c0c33R25

**Closed as completed by geudrik** 2020-07-03 17:46 UTC
Labels: bug
